#############################################################################
# Makefile for building: QHBot
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Jun 16 09:05:02 2012
# Project:  QHBot.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile QHBot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtNetwork -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include -Iqxmpp/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lqxmpp -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qhbot.cpp \
		qhbotuser.cpp \
		qhbotusermanager.cpp \
		qhbotcommands.cpp \
		qhbotdatamanager.cpp moc_qhbot.cpp \
		moc_qhbotuser.cpp \
		moc_qhbotusermanager.cpp \
		moc_qhbotcommands.cpp \
		moc_qhbotdatamanager.cpp
OBJECTS       = main.o \
		qhbot.o \
		qhbotuser.o \
		qhbotusermanager.o \
		qhbotcommands.o \
		qhbotdatamanager.o \
		moc_qhbot.o \
		moc_qhbotuser.o \
		moc_qhbotusermanager.o \
		moc_qhbotcommands.o \
		moc_qhbotdatamanager.o
DIST          = /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		QHBot.pro
QMAKE_TARGET  = QHBot
DESTDIR       = 
TARGET        = QHBot

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QHBot.pro  /usr/lib64/qt4/mkspecs/linux-g++/qmake.conf /usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt4/mkspecs/common/g++-base.conf \
		/usr/lib64/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtXml.prl \
		/usr/lib64/libQtCore.prl \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtNetwork.prl
	$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile QHBot.pro
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base.conf:
/usr/lib64/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt4/mkspecs/common/g++-base.conf:
/usr/lib64/qt4/mkspecs/common/g++-unix.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtXml.prl:
/usr/lib64/libQtCore.prl:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib64/qt4/mkspecs/linux-g++ -o Makefile QHBot.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QHBot1.0.0 || $(MKDIR) .tmp/QHBot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QHBot1.0.0/ && $(COPY_FILE) --parents qhbot.h qhbotuser.h qhbotusermanager.h qhbotcommands.h qhbotdatamanager.h .tmp/QHBot1.0.0/ && $(COPY_FILE) --parents main.cpp qhbot.cpp qhbotuser.cpp qhbotusermanager.cpp qhbotcommands.cpp qhbotdatamanager.cpp .tmp/QHBot1.0.0/ && (cd `dirname .tmp/QHBot1.0.0` && $(TAR) QHBot1.0.0.tar QHBot1.0.0 && $(COMPRESS) QHBot1.0.0.tar) && $(MOVE) `dirname .tmp/QHBot1.0.0`/QHBot1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QHBot1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qhbot.cpp moc_qhbotuser.cpp moc_qhbotusermanager.cpp moc_qhbotcommands.cpp moc_qhbotdatamanager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qhbot.cpp moc_qhbotuser.cpp moc_qhbotusermanager.cpp moc_qhbotcommands.cpp moc_qhbotdatamanager.cpp
moc_qhbot.cpp: qhbot.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) qhbot.h -o moc_qhbot.cpp

moc_qhbotuser.cpp: qhbotuser.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) qhbotuser.h -o moc_qhbotuser.cpp

moc_qhbotusermanager.cpp: qhbotusermanager.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) qhbotusermanager.h -o moc_qhbotusermanager.cpp

moc_qhbotcommands.cpp: qhbotcommands.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) qhbotcommands.h -o moc_qhbotcommands.cpp

moc_qhbotdatamanager.cpp: qhbotdatamanager.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) qhbotdatamanager.h -o moc_qhbotdatamanager.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp qhbot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qhbot.o: qhbot.cpp qhbot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhbot.o qhbot.cpp

qhbotuser.o: qhbotuser.cpp qhbotuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhbotuser.o qhbotuser.cpp

qhbotusermanager.o: qhbotusermanager.cpp qhbotusermanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhbotusermanager.o qhbotusermanager.cpp

qhbotcommands.o: qhbotcommands.cpp qhbotcommands.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhbotcommands.o qhbotcommands.cpp

qhbotdatamanager.o: qhbotdatamanager.cpp qhbotdatamanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qhbotdatamanager.o qhbotdatamanager.cpp

moc_qhbot.o: moc_qhbot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhbot.o moc_qhbot.cpp

moc_qhbotuser.o: moc_qhbotuser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhbotuser.o moc_qhbotuser.cpp

moc_qhbotusermanager.o: moc_qhbotusermanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhbotusermanager.o moc_qhbotusermanager.cpp

moc_qhbotcommands.o: moc_qhbotcommands.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhbotcommands.o moc_qhbotcommands.cpp

moc_qhbotdatamanager.o: moc_qhbotdatamanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qhbotdatamanager.o moc_qhbotdatamanager.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

